### ISSUE TITLE
1vs1 support

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaWilliam/ActionFPS#136]

**Comment by Paul255** [comment]
!1v1 ?

**Comment by lucasgautheron** [comment]
@Paul255  what ?

The first step is a simple "feasibility study" of 1vs1 integration, given the current data.
Basically, figure out if there is a good set of filters that can extract 1vs1s with the minimal amounts of fake and loss. *This is more difficult than it is with X vs X games*. 1vs1's are more likely to produce fakes, because it is easy for one player to score a lot, while the other is AFK. I suggest the following : 
 * "Strict" quality requirements for games until today : 
    * 10 minute DM/OSOK/SURV game
    * at least 10 frags on each player
    * Only 2 players, ofc.

 * Then we can implement something on the server that outputs idle times for each player in the logs at the end of the game, e.g. : 
```
[127.0.0.1] w00p|Drakas idle time: 8 s
[127.0.0.1] w00p|Lucas idle time: 60 s
```

 And require only 1 frag on each player, plus an idle time lower than a certain value for every player.

**Comment by Paul255** [comment]
Yeah I understand, but I don't think It's possible to make it with filters.
Sometime you just want to play 1v1 for fun, warmup etc ... If every 1v1s are counted in the elo calculation It could discourage player from playing 1v1 on our servers.

Whereas if you implement a "!1v1" command (which count the next map as a 1v1 under simples conditions -> 10 mins;1v1) It would encourage players to duel on our servers.

**Comment by lucasgautheron** [comment]
We haven't talked about counting them into ELO calculation. We could have a 1v1 ranking though. We're just talking about collecting these games

**Comment by ScalaWilliam** [comment]
Any progress on this? ;)

**Comment by lucasgautheron** [comment]
I'm not planning to work on this any soon (IRL #1, client #2, rest is #3).
I can code the idle time calculator though if you need it, but you probably
don't for now.
ATM it's all up to Paul, if he feels like doing it.

2016-02-15 8:42 GMT+01:00 Vykintas Narmontas (William) <
notifications@github.com>:
