### ISSUE TITLE
ActionFPS Blog WordPress

### ISSUE THREAD

**Issue by DaylixX** [ScalaWilliam/ActionFPS#287]
- What do you need on the Blog ?
- Let's use it over the long term ?
-  We use it just for #tournaments or more ?

**Comment by DaylixX** [comment]
Added : list of Serveres / FAQ (Wiki) / Connect on Discord / Contact

What we need more on the blog ?

**Comment by ScalaWilliam** [comment]
The purpose of the blog is just to update people on what is happening in a more permanent fashion than Discord. But more permanent things like documentation should live somewhere else.

## Comments 

I'm still debating where we put the long term documentation and peoples questions & answers. Problem with Discord is that things are very short lived and will require a lot of repetition. Problem with using Wordpress is our communication will be spread throughout many different places. So I have been trying to put documentation into the GitHub Wiki, and peoples questions could go to GitHub Issues - maybe a separate repository or maybe this repository.

When somebody has a tournament question, they ask on GitHub Issue, we answer it there, and then put the answer into the Wiki, and from then, direct people to the Wiki.

So perhaps we disable Wordpress comments and divert them to this Issues page where everyone can discuss in a common place and be closer to the code to encourage contributions.

## Content, like servers, etc

These should be **external links** to the Wiki. What happens when we update the content in one place? Then we have to update it in another place, etc. A lot of work!

However I do like the fact that Wordpress is prettier with this - and I'm still not settled on WP being the right platform just yet as we have GitHub available after all that can do hosting AND wiki management, etc. This may not actually be final. https://actionfps.wordpress.com/faq/ looks nicer than https://github.com/ScalaWilliam/ActionFPS/wiki/Frequently-Asked-Questions - **BUT** keeps people further away from the code.


So: 

    Comments and questions? Post an Issue to the ActionFPS GitHub: https://github.com/ScalaWilliam/ActionFPS/issues
    Also see Frequently Asked Questions on ActionFPS GitHub Wiki: https://github.com/ScalaWilliam/ActionFPS/wiki/Frequently-Asked-Questions

**Comment by ScalaWilliam** [comment]
Every single page should link to: 
1. FAQ on Wiki
2. GitHub Issues
3. Discord

In this order :)

**Comment by DaylixX** [comment]
Done ! https://actionfps.wordpress.com/

**Comment by ScalaWilliam** [comment]
Report an Issue -> Maybe 'Ask for help'?

There is an issue when you need to ask for help - it is an issue, but not necessarily something to "report" ;)

**Comment by ScalaWilliam** [comment]
PS redirect for the servers page as well :)

**Comment by DaylixX** [comment]
Done !

**Comment by ScalaWilliam** [comment]
Perfect 👍 it looks very nice, simple and minimalistic.

If you're happy would you close the ticket?

**Comment by DaylixX** [comment]
Ok closed
