### ISSUE TITLE
Log stream has duplicate entries sometimes

### ISSUE THREAD

**Issue by jasbrake** [ScalaWilliam/ActionFPS#406]
When I'm streaming the logs, sometimes I'll see duplicate entries. For example:
```
2017-07-13T02:59:18Z    62-210-131-155.rev.poneytelecom.eu aura AssaultCube[local#2999] [0.0.0.0] Pi_Minion logged in (default), AC: 1202|1e40
2017-07-13T02:59:18Z    62-210-131-155.rev.poneytelecom.eu aura ac_server_stream[16312] Jul 13 04:59:18 [186.53.42.x] Pi_Minion logged in (default), AC: 1202|1e40
```
Clearly 1 is from `ac_server_stream[16312]`, and the other is from `AssaultCube[local#2999]`. In addition, even when not authenticating with any token, the lines from ac_server_stream are not stripped of full IPs.

**Comment by ScalaWilliam** [comment]
the IP thing should be a separate issue... the token too :-)

**Comment by ScalaWilliam** [comment]
Now onto duplicates - the server ID is different so shouldn't cause a problem. Notice how there's no `#2999` in the second line and also it contains an extra timestamp in the payload. This is because of systemd logging. I could prevent this problem by only filtering out what we consider as "valid servers". This functionality should actually be implemented, IMO.

**Comment by jasbrake** [comment]
Yes I could work around it if I had to. However, I don't see any reason for it to be there in the first place so I agree that the functionality should be implemented.

**Comment by ScalaWilliam** [comment]
@jasbrake I have a list of allowed servers.

In the new version of actionfps-syslog, this issue does not happen any more, so you will see it disappear when we switch over.

The reason why there are "duplicates", is actually because systemd logs process output with PID in the same stream.

I'll close, as we're almost there.
